COMPANIES = [
    {"name": "Ciena", "ats": "workday", "tenant": "ciena", "dc": "wd5", "site": "Careers"},
    {"name": "BlackBerry", "ats": "workday", "tenant": "bb", "dc": "wd3", "site": "BlackBerry"},
    {"name": "TD Bank", "ats": "workday", "tenant": "td",   "dc": "wd3", "site": "TD_Bank_Careers"},
    {"name": "CIBC", "ats": "workday", "tenant": "cibc", "dc": "wd3", "site": "campus"},
    {"name": "Fullscript", "ats": "lever", "slug": "fullscript"},
    {"name": "Solace", "ats": "ashby", "slug": "solace"},
    {"name": "Rewind", "ats": "ashby", "slug": "rewind"},
    {"name": "Mitel", "ats": "workday", "tenant": "mitel", "dc": "wd3", "site": "mitelcareers"},
    {"name": "Accenture", "ats": "workday", "tenant": "accenture", "dc": "wd103", "site": "accenturecareers"},
    {"name": "BDO", "ats": "workday", "tenant": "bdo", "dc": "wd3", "site": "BDO"},
    {"name": "PwC",        "ats": "workday",        "tenant": "pwc",    "dc": "wd3", "site": "Global_Campus_Careers"},
    {"name": "Thales",     "ats": "workday",        "tenant": "thales", "dc": "wd3", "site": "Careers"},
    {"name": "ServiceNow", "ats": "smartrecruiters", "slug": "servicenow"},
    {"name": "Assent",     "ats": "smartrecruiters", "slug": "assent"},
    {"name": "Nuvei",      "ats": "workable",        "account_id": "378737"},
]